config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :users do
    resources :posts do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

require 'action_view'

# no-doc
class Comment < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  after_create_commit { broadcast_append_to 'comments' }
  after_update_commit { broadcast_replace_to 'comments' }
  after_destroy_commit { broadcast_remove_to 'comments' }

  def created_time_ago
    time_ago_in_words(created_at)
  end
end

app/models/post.rb
# frozen_string_literal: true

require 'action_view'

# no-doc
class Post < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def created_time_ago
    time_ago_in_words(created_at)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_out_path_for(_)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# nodoc
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[new create]
  before_action :set_comment, only: %i[show edit update]
  before_action :authorize_user!, only: %i[edit update]

  def new
    @comment = @post.comments.new(user: current_user)
  end

  def edit; end

  def create
    @comment = @post.comments.new(comment_params.merge(user: current_user))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@comment.user, @comment.post], notice: 'Comment was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@comment, partial: 'comments/form', locals: { comment: @comment })
        end
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@comment.user, @comment.post], notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to [@post.user, @post], notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authorize_user!
    raise 'Unauthorized' unless @comment.user == current_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# no-doc
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# nodoc
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_poster, only: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @poster.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.turbo_stream
        format.html { redirect_to [current_user, @post], notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [current_user, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_poster
    @poster = User.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# nodoc
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to current_user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <p><%= comment.content %></p>
  <p>
    <small>
      <%= comment.user.email %>
      &middot;
       <%= comment.created_time_ago %>
    </small>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag 'new_comment', target: '_top' do %>
  <%= form_with(model: [current_user, comment.post, comment],
                data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :content, 'Comment' %>
      <%= form.text_area :content %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit', data: { disable_with: false } %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h2>Editing Comment</h2>

<%= turbo_frame_tag @comment do %>
  <%= render 'form', comment: @comment %>
  <%= link_to 'Cancel', [@comment.user, @comment.post] %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', user_post_path(@post.user, @post) %>

app/views/comments/show.html.erb
<%= render @comment %>
<%= link_to 'Edit', edit_user_post_comment_path(current_user, comment.post, comment) %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<div class="all-posts">
  <div>
    <h1>All Posts</h1>
  </div>

  <div>
    <div class="new-post">
      <%= turbo_frame_tag 'new_post', src: new_user_post_path(current_user), target: '_top' %>
    </div>

    <ul id="posts">
      <%= render @posts %>
    </ul>
  </div>
</div>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <nav class="user-nav"> 
    <%= link_to 'Home', root_path %>
    <%= link_to 'Users', users_path %>
    <%= link_to current_user.email, user_path(current_user) %>
  </nav>
  <div class="user-session-control">
    Signed in as <b><%= current_user.email %></b>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [post.user, post],
              data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, size: '25x5' %>
  </div>

  <div class="actions">
    <%= form.submit 'Post', data: { disable_with: false } %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
  <div class="post-item">
    <div>
      <span class="content">
        <%= link_to truncate(post.content, length: 100), [post.user, post] %> 
      </span>
      <div class="content-info">
        <span class="author"><%= post.user.email %></span>
        &middot;
        <span class="timestamp"><%= post.created_time_ago %></span>
      </div>
    </div>
  <div>
</li>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", @post %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= turbo_frame_tag "post" do %>
  <%= render 'form', post: @post %>
<% end %>
<%= link_to 'Back', [current_user, @post] %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<ul id="posts">
    <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= turbo_frame_tag 'new_post' do %>
  <%= render 'form', post: @post %>
<% end %>

<%= link_to 'Back', user_posts_path(@post.user) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post">
  <%= turbo_frame_tag "post" do %>
    <p>
      <big>
        <%= @post.content %>
      </big>
    </p>

    <p>
      <small>
        <%= link_to "#{@post.user.email}", @post.user, target: '_top' %>
        &middot;
        <%= @post.created_at.to_formatted_s(:short) %>
      </small>
    </p>
    <% if @post.user == current_user %>
      <%= link_to 'Edit', edit_user_post_path(@post.user, @post) %> |
      <%= link_to 'Delete', user_post_path(@post.user, @post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
</div>

<div class="comments">
  <%= turbo_stream_from "comments" %>
  <%= turbo_frame_tag "comments" do %>
    <h2>Comments</h2>
    <%= render @post.comments %>
  <% end %>

  <%= turbo_frame_tag 'new_comment', src: new_user_post_comment_path(@post.user, @post), target: '_top' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="actions">
    <%= form.submit 'Save'%>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <span class="email">
    <%= link_to user.email, user %> 
  </span
</li>

app/views/users/edit.html.erb
<%= turbo_frame_tag "user" do %>
  <%= render 'form', user: @user %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="all-users">
  <div>
    <h1>All Users</h1>
  </div>

  <div>
    <ul id="users">
      <%= render @users %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="user-posts">
  <div class="user">
    <h2><%= @user.email %></h2>

    <%= turbo_frame_tag "user" do %>
      <% if @user.about.present? %>
        <div class="about">
          About
          <p><%= @user.about %></p>
        </div>
      <% end %>

      <div class="actions">
        <% if @user == current_user %>
          <%= link_to 'Edit', edit_user_path(@user) %> 
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="posts">
    <% if @user == current_user %>
      <div class='new-post'>
        <%= turbo_frame_tag 'new_post', src: new_user_post_path(current_user), target: '_top' %>
      </div>
    <% end %>

    <ul id="posts">
      <%= render @user.posts %>
    </ul>
  </div>
</div>